services:
  mysql:
    image: 'mysql:8.0'
    container_name: db_app
    volumes:
      - './sql/images:/sql_images'
      - 'database_storange:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=app
    ports:
      - '8002:3306'
    networks:
      - kurs_api

  server:
    image: 'nginx:alpine'
    container_name: nginx_app
    working_dir: /var/www
    volumes:
      - '.:/var/www'
      - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '8089:80'
    networks:
        - kurs_api

  php-fpm:
    build: docker/php
    container_name: php_app
    working_dir: /var/www
    volumes:
      - '.:/var/www'
      - './docker/php/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
    networks:
      - kurs_api

networks:
  kurs_api:
    driver: bridge
    #external: true

volumes:
  database_storange:
